
name: Deploy the documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # If your documentation requires Git submodules, uncomment the next line
          # submodules: true

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          corepack enable
          npm ci

      - name: Build documentation
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: Depoloy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Depoloy documentation
          branch: gh-pages
          folder: src/.vuepress/dist
